apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-dep-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tom-container
          image: armcool004/maven-web-testing-1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tom-ser
spec:
  type: LoadBalancer
  selector:
    app: tomcat-app
  ports:
    - port: 80
      targetPort: 8080
